# Generated by Django 5.1.7 on 2025-03-16 11:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('program_type', models.CharField(choices=[('RESIDENCY', 'Residency'), ('FELLOWSHIP', 'Fellowship')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('GME_STAFF', 'GME Staff'), ('PROGRAM_DIRECTOR', 'Program Director'), ('INTERVIEWER', 'Interviewer'), ('APPLICANT', 'Applicant')], max_length=20)),
                ('department', models.CharField(blank=True, choices=[('INTERNAL_MEDICINE', 'Internal Medicine Department'), ('PEDIATRICS', 'Pediatrics Department'), ('GENERAL_SURGERY', 'General Surgery Department'), ('RADIATION_ONCOLOGY', 'Radiation Oncology Department'), ('PATHOLOGY', 'Pathology and Laboratory Medicine Department'), ('NUCLEAR_MEDICINE', 'Nuclear Medicine Department'), ('DIAGNOSTIC_RADIOLOGY', 'Diagnostic Radiology Department'), ('ANESTHESIA', 'Anesthesia Department')], max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('is_approved', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_en', models.CharField(max_length=50)),
                ('second_name_en', models.CharField(max_length=50)),
                ('third_name_en', models.CharField(max_length=50)),
                ('last_name_en', models.CharField(max_length=50)),
                ('first_name_ar', models.CharField(max_length=50)),
                ('second_name_ar', models.CharField(max_length=50)),
                ('third_name_ar', models.CharField(max_length=50)),
                ('last_name_ar', models.CharField(max_length=50)),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=100)),
                ('gpa', models.FloatField()),
                ('national_id_document', models.FileField(upload_to='documents/national_id/')),
                ('cv', models.FileField(upload_to='documents/cv/')),
                ('payment_receipt', models.FileField(upload_to='documents/payment/')),
                ('university_certificate', models.FileField(upload_to='documents/certificates/')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ELIGIBLE', 'Eligible'), ('NOT_ELIGIBLE', 'Not Eligible'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.program')),
            ],
            options={
                'unique_together': {('applicant', 'program')},
            },
        ),
    ]
