# Generated by Django 5.1.7 on 2025-03-17 06:30

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cv',
            field=models.FileField(upload_to=users.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='application',
            name='national_id_document',
            field=models.FileField(upload_to=users.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='application',
            name='payment_receipt',
            field=models.FileField(upload_to=users.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='application',
            name='university_certificate',
            field=models.FileField(upload_to=users.models.get_file_path),
        ),
    ]
