# Generated by Django 5.1.7 on 2025-03-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_application_cv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
