# Generated by Django 5.1.7 on 2025-03-17 07:19

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_program_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cv',
            field=models.FileField(upload_to=users.models.Application.cv_upload_path),
        ),
        migrations.AlterField(
            model_name='application',
            name='national_id_document',
            field=models.FileField(upload_to=users.models.Application.national_id_upload_path),
        ),
        migrations.AlterField(
            model_name='application',
            name='payment_receipt',
            field=models.FileField(upload_to=users.models.Application.payment_upload_path),
        ),
        migrations.AlterField(
            model_name='application',
            name='university_certificate',
            field=models.FileField(upload_to=users.models.Application.certificate_upload_path),
        ),
    ]
