# Generated by Django 5.1.7 on 2025-03-17 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_application_cv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
    ]
