# Generated by Django 3.2.25 on 2025-03-17 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='test_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ELIGIBLE', 'Eligible'), ('NOT_ELIGIBLE', 'Not Eligible'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('INVITED_FOR_INTERVIEW', 'Invited for Interview')], default='SUBMITTED', max_length=25),
        ),
        migrations.CreateModel(
            name='InterviewScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_type', models.CharField(choices=[('RESIDENCY', 'Residency'), ('FELLOWSHIP', 'Fellowship')], max_length=20)),
                ('professional_appearance', models.PositiveSmallIntegerField(default=0)),
                ('interest', models.PositiveSmallIntegerField(default=0)),
                ('behavior', models.PositiveSmallIntegerField(default=0)),
                ('future_plans', models.PositiveSmallIntegerField(default=0)),
                ('personality', models.PositiveSmallIntegerField(default=0)),
                ('handling_emergencies', models.PositiveSmallIntegerField(default=0)),
                ('professional_attitude', models.PositiveSmallIntegerField(default=0)),
                ('knowledge', models.PositiveSmallIntegerField(default=0)),
                ('research', models.PositiveSmallIntegerField(default=0)),
                ('tentative_available_date', models.DateField(blank=True, null=True)),
                ('interview_score', models.FloatField(default=0)),
                ('medical_school_score', models.FloatField(default=0)),
                ('total_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview_score', to='users.application')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_interviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
