# Generated by Django 3.2.25 on 2025-03-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20250317_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='is_draft',
        ),
        migrations.RemoveField(
            model_name='application',
            name='test_score',
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ELIGIBLE', 'Eligible'), ('NOT_ELIGIBLE', 'Not Eligible'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=15),
        ),
        migrations.DeleteModel(
            name='InterviewScore',
        ),
    ]
