# Generated by Django 3.2.25 on 2025-03-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20250317_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='gpa',
            field=models.CharField(choices=[('SATISFACTORY', 'Satisfactory'), ('GOOD', 'Good'), ('VERY_GOOD', 'Very Good'), ('EXCELLENT', 'Excellent')], max_length=20),
        ),
    ]
