# Generated by Django 5.1.7 on 2025-03-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_application_gpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='final_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='final_score_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='final_score_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='final_score_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
