# Generated by Django 5.1.7 on 2025-03-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_application_final_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='flexibility_teamwork',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interview',
            name='leadership',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interview',
            name='problem_solving',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interview',
            name='stress_coping',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interview',
            name='takes_feedback',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interview',
            name='time_management',
            field=models.SmallIntegerField(default=0),
        ),
    ]
