# Generated by Django 5.1.7 on 2025-03-19 08:49

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_interview_flexibility_teamwork_interview_leadership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='board_certification',
            field=models.FileField(blank=True, null=True, upload_to=users.models.Application.board_certification_upload_path),
        ),
        migrations.AlterField(
            model_name='application',
            name='payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to=users.models.Application.payment_upload_path),
        ),
        migrations.AlterField(
            model_name='application',
            name='university_certificate',
            field=models.FileField(blank=True, null=True, upload_to=users.models.Application.certificate_upload_path),
        ),
    ]
