# Generated by Django 5.0.6 on 2024-04-09 13:30

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_application_board_certification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.profile_picture_upload_path),
        ),
    ] 