# Generated by Django 5.0.6 on 2024-04-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('ELIGIBLE', 'Eligible'), ('NOT_ELIGIBLE', 'Not Eligible'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WAIT_LISTED', 'Waitlisted'), ('INVITED_FOR_INTERVIEW', 'Invited for Interview')], default='SUBMITTED', max_length=25),
        ),
    ] 