# Generated by Django 5.1.7 on 2025-03-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='additional_info',
            field=models.TextField(blank=True, help_text='Any additional information you would like to provide.', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='personal_statement',
            field=models.TextField(blank=True, help_text='Explain why you are interested in this program and why you would be a good fit.', null=True),
        ),
    ]
