# Generated by Django 5.1.7 on 2025-03-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('internal_medicine', 'Internal Medicine Department'), ('pediatrics', 'Pediatrics Department'), ('general_surgery', 'General Surgery Department'), ('radiation_oncology', 'Radiation Oncology Department'), ('pathology', 'Pathology and Laboratory Medicine Department'), ('nuclear_medicine', 'Nuclear Medicine Department'), ('diagnostic_radiology', 'Diagnostic Radiology Department'), ('anesthesia', 'Anesthesia Department')], max_length=30)),
                ('program_type', models.CharField(choices=[('residency', 'Residency'), ('fellowship', 'Fellowship')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('capacity', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
